### ISSUE TITLE
Support for .net core 3?

### ISSUE THREAD

**Issue by ravensorb** [JeevanJames/IniFile#26]
I was curious if there are any plans to support .netcore 3.1?

**Comment by JeevanJames** [comment]
@ravensorb The library target `.netstandard2.0`, which can be used by .NET Core 3.1 projects.

Is there anything specific from .netcore 3.1 that you require?

**Comment by ravensorb** [comment]
I am working on a number of .net core apps on linux (mint and ubuntu) and it seems that .netstandard2.0 has some peculiar issues that are addressed with straight net core 3.1

**Comment by JeevanJames** [comment]
Could you provide some details on the problems you're facing (or some links I can look at)? I'd like to better understand the problem before attempting a solution.

While I could add a target for `netcore3.1` to the project, this would only solve the problem for .NET Core 3.1 apps. I would need to know whether to also target `netcore3.0`, `netcore2.2`, etc. Or could I target an acceptable lowest .NET Core target like `netcore2.0`.

My confusion stems from the fact that `netstandard` is just a specification for the implementations like `netcore3.1` to follow; there is no separate `netstandard` implementation.
